(function() {
  'use strict';

    angular.module('moi')
      .value('Interests',
        [
          {
            interest:'Animales',
            src:'images/animal-interest.png'
          },
          {
            interest:'Lugares',
            src:'images/places-interest.png'
          },
          {
            interest:'Deportes',
            src:'images/sports-interest.png'
          },
          {
            interest:'Comunicacion',
            src:'images/comunication-interest.png'
          },
          {
            interest:'Cuentos',
            src:'images/stories-interest.png'
          },
          {
            interest:'Arte',
            src:'images/art-interest.png'
          },
          {
            interest:'Emociones',
            src:'images/emotions-interest.png'
          },
          {
            interest:'Cultura',
            src:'images/culture-interest.png'
          },
          {
            interest:'Espacio',
            src:'images/space-interest.png'
          },
          {
            interest:'Numeros',
            src:'images/numbers-interest.png'
          },
          {
            interest:'Cerebro',
            src:'images/brain-interest.png'
          },
          {
            interest:'Plantas',
            src:'images/plants-interest.png'
          }
        ]
      );
  })();
