(function() {
  'use strict';

    angular.module('moi')
      .value('InterestsEn',
        [
          {
            interest:'Animals',
            src:'images/animal-interest.png'
          },
          {
            interest:'Places',
            src:'images/places-interest.png'
          },
          {
            interest:'Sports',
            src:'images/sports-interest.png'
          },
          {
            interest:'Communication',
            src:'images/comunication-interest.png'
          },
          {
            interest:'Stories',
            src:'images/stories-interest.png'
          },
          {
            interest:'Art',
            src:'images/art-interest.png'
          },
          {
            interest:'Emotions',
            src:'images/emotions-interest.png'
          },
          {
            interest:'Culture',
            src:'images/culture-interest.png'
          },
          {
            interest:'Space',
            src:'images/space-interest.png'
          },
          {
            interest:'Numbers',
            src:'images/numbers-interest.png'
          },
          {
            interest:'Brain',
            src:'images/brain-interest.png'
          },
          {
            interest:'Plants',
            src:'images/plants-interest.png'
          }
        ]
      );
  })();
